name: Deploy Blog
on:
  push:
    branches:
      - master
jobs:
  deploy-blog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
        aws-region: us-east-1
    - name: Configure Ruby version
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install bundler
      run: gem install bundler
    - name: Install dependencies
      run: bundle install
    - name: Generate website
      run: bundle exec jekyll build
    - name: Deploy static blog to S3 bucket
      run: aws s3 sync ./_site/ s3://rafaaudibert-blog --delete